Update paths for ArcGIS.xcframework
Esri/maps-app-ios pull request #106
Opened 2020-11-11 22:53 UTC by mhdostal

Update paths for ArcGIS.xcframework as the next release of the ArcGIS SDK now builds a binary framework.

2020-11-11 22:54 UTC, mhdostal commented
Includes automatic project updates for Xcode 12

2020-11-17 18:59 UTC, esreli reviewed
It looks like this file could use the same treatment applied in the Data Collection iOS repo.
https://github.com/Esri/data-collection-ios/pull/258#issuecomment-726925598

2020-11-17 18:59 UTC, esreli commented on RELEASE.md
> +- The 100.10.0 release of the ArcGIS Runtime for iOS is now distributed as a binary framework.  This necessitated the following changes in the Maps App Xcode project file:
```suggestion
- The 100.10 release of the ArcGIS Runtime for iOS is now distributed as a binary framework.  This necessitated the following changes in the Maps App Xcode project file:
```

2020-11-17 18:59 UTC, esreli commented on RELEASE.md
> +- Certification for the 100.10.0 release of the ArcGIS Runtime SDK for iOS.
```suggestion
- Certification for the 100.10 release of the ArcGIS Runtime SDK for iOS.
```

2020-11-18 18:34 UTC, esreli requested changes

2020-11-18 18:34 UTC, esreli commented on maps-app-ios.xcodeproj/project.pbxproj
> +			shellScript = "if [ -e $HOME/.runtime-example-apps/xcode-run-scripts/arcgis-build-number-run-script.sh ]; then\n$HOME/.runtime-example-apps/xcode-run-scripts/arcgis-build-number-run-script.sh -p i
Would you get rid of the second build script, like you did for Data Collection?

2020-11-18 19:13 UTC, esreli requested changes
Would you update the app marketing version to match the release version?

2020-11-18 21:12 UTC, esreli approved these changes

2020-11-19 19:01 UTC, merged